//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElophantClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElophantClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap E_Huge {
            get {
                object obj = ResourceManager.GetObject("E_Huge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noise {
            get {
                object obj = ResourceManager.GetObject("noise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] prod_br_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_br_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] prod_eu_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_eu_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] prod_eun1_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_eun1_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] prod_na1_lol_riotgames_com {
            get {
                object obj = ResourceManager.GetObject("prod_na1_lol_riotgames_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;WIN&quot;:&quot;Victories&quot;,
        ///	&quot;CHAMPIONS_KILLED&quot;:&quot;Champion Kills&quot;,
        ///	&quot;TOTAL_ASSISTS&quot;:&quot;Assists&quot;,
        ///	&quot;FRIENDLY_HQ_LOST&quot;:&quot;Friendly Nexus Destroyed&quot;,
        ///	&quot;TOTAL_TIMES_SPELL4_CAST&quot;:&quot;Spell 4 Casts&quot;,
        ///	&quot;UNREAL_KILLS&quot;:&quot;Unreal Kills&quot;,
        ///	&quot;MAX_CHAMPIONS_KILLED&quot;:&quot;Max Kills&quot;,
        ///	&quot;TOTAL_PLAYER_SCORE&quot;:&quot;Total Score&quot;,
        ///	&quot;SPELL2_CAST&quot;:&quot;Spell 2 Casts&quot;,
        ///	&quot;TOTAL_CHAMPION_KILLS&quot;:&quot;Total Champion Kills&quot;,
        ///	&quot;EXP&quot;:&quot;Champion Experience&quot;,
        ///	&quot;MINIONS_KILLED&quot;:&quot;Minions Slain&quot;,
        ///	&quot;MAGIC_DAMAGE_TAKEN&quot;:&quot;Magic Damage Taken&quot;,
        ///	&quot;SUPER_MONSTER_KILLED&quot;:&quot;Epic Monster [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatsData {
            get {
                return ResourceManager.GetString("StatsData", resourceCulture);
            }
        }
    }
}
